<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="projectfinal.WebForm1" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Data from CSV</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>

            <asp:GridView ID="GridView1" runat="server" DataKeyNames="單位名稱" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateDeleteButton="true">
            </asp:GridView>
        </div>
        <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse">
            <tr>
                <td style="width: 150px">單位名稱:<br />
                    <asp:TextBox ID="txtName" runat="server" Width="140" />
                </td>
                <td style="width: 150px">郵遞區號:<br />
                    <asp:TextBox ID="txtPost" runat="server" Width="140" />
                </td>
                <td style="width: 150px">地址:<br />
                    <asp:TextBox ID="txtAddr" runat="server" Width="140" />
                </td>
                <td style="width: 150px">市話:<br />
                    <asp:TextBox ID="txtPhone" runat="server" Width="140" />
                </td>
                <td style="width: 150px">
                    <asp:Button ID="btnAdd" runat="server" Text="Add" OnClick="Insert" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
