// <auto-generated />
using System;
using Kcg.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kcg.Migrations
{
    [DbContext(typeof(KcgContext))]
    [Migration("20240727090341_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kcg.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "交通局"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "工務局"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Name = "農業局"
                        });
                });

            modelBuilder.Entity("Kcg.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 1,
                            Name = "王大明"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 2,
                            Name = "林曉明"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentId = 3,
                            Name = "陳芸芸"
                        });
                });

            modelBuilder.Entity("Kcg.Models.News", b =>
                {
                    b.Property<Guid>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("Click")
                        .HasColumnType("int");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("Enable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("EndDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("InsertDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("InsertEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UpdateEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("NewsId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            NewsId = new Guid("ac18009b-b2e7-4bec-bc0a-8cc301a81fe9"),
                            Click = 61,
                            Contents = "楠梓火車站是楠梓與周邊地區的運輸門戶，鄰近工業區、加工出口區、高雄科技大學、高雄都會公園等，形成機能豐富的生活圈。為提升楠梓區域旅運與民生往來品質，市府工務局道路養護工程處針對車站周邊人行道進行改善，已陸續整新楠梓新路東側（建楠路至楠梓區公所）、建楠路（全線）人行道，楠梓新路西側（建楠路至惠民捷道）人行道改善也接續於今（113）年6月底進場施做。",
                            DepartmentId = 2,
                            Enable = true,
                            EndDateTime = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertDateTime = new DateTime(2024, 7, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertEmployeeId = 2,
                            StartDateTime = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "楠梓火車站周邊人行道改善 提升通行舒適度",
                            UpdateDateTime = new DateTime(2024, 7, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateEmployeeId = 2
                        },
                        new
                        {
                            NewsId = new Guid("4d9b4c16-98de-40bc-9267-1f2e754bc2b8"),
                            Click = 261,
                            Contents = "翠亨路是前鎮、小港區的幹道之一，也是兩地居民往返高雄市區的重要道路，翠亨路早期原有台糖運送貨物鐵道，經市府工務局改造成自行車道後，逐步升級周邊街景，從日常的設施維護改善、綠美化到專案辦理鐵道意象改造設置觀機平台、花架綠廊與翠平公園旁閒置空地環境再造等，近期再接力完成翠亨南路（平和東路至崇安街）路面改善及高雄國際花卉市場南側空地景觀營造，以提升區域生活品質、優化高市迎賓門戶整體風貌。",
                            DepartmentId = 2,
                            Enable = true,
                            EndDateTime = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertDateTime = new DateTime(2024, 7, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertEmployeeId = 2,
                            StartDateTime = new DateTime(2024, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "高雄國際花卉市場周邊道路景觀整建 營造舒適綠空間",
                            UpdateDateTime = new DateTime(2024, 7, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateEmployeeId = 2
                        },
                        new
                        {
                            NewsId = new Guid("a780e4d9-7742-4736-a395-340929e2dfa9"),
                            Click = 161,
                            Contents = "【高雄訊】夏日日頭赤炎炎，機車族在停等沒有綠蔭的路口紅燈時，不免會有為何不能縮短秒數，減少停等曝曬時間的想法。高雄市交通局表示，7月起逐步於三民區以及苓雅區部分路段試辦縮短號誌週期秒數，可減少紅燈停等時的陽光曝曬時間，交通局也會持續觀察車流紓解狀況，適時檢討調整。",
                            DepartmentId = 1,
                            Enable = true,
                            EndDateTime = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertDateTime = new DateTime(2024, 7, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertEmployeeId = 1,
                            StartDateTime = new DateTime(2024, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "夏日氣溫炎熱！交通局研擬調整號誌秒數，縮短停等時間。",
                            UpdateDateTime = new DateTime(2024, 7, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateEmployeeId = 1
                        },
                        new
                        {
                            NewsId = new Guid("b3bff517-d479-4c2b-84e8-a43e541a02b3"),
                            Click = 1561,
                            Contents = "【高雄訊】近日高雄青年路(復興-林森)如火如荼進行道路重鋪工程，有眼尖民眾發現標線繪製線條與之前不一樣，高雄市交通局特別說明，因施工範圍長，道路兩側寬度不同處，在施工過程中依實地狀況做適時調整，並重新分配車道空間，為了交通安全，這都是必要的工作。",
                            DepartmentId = 1,
                            Enable = true,
                            EndDateTime = new DateTime(2025, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertDateTime = new DateTime(2024, 7, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertEmployeeId = 1,
                            StartDateTime = new DateTime(2024, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "青年路家具街增設左轉車道及路面邊線，有效界定車流動線、安全再升級！",
                            UpdateDateTime = new DateTime(2024, 7, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateEmployeeId = 1
                        },
                        new
                        {
                            NewsId = new Guid("00de1a6a-77c9-4a20-b353-da9167c8f311"),
                            Click = 1161,
                            Contents = "高雄出產的新鮮紅心芭樂持續進入馬來西亞吉隆坡市場，今年度首次上架新開張的高端超市「Imby Greens」，該超市位於馬來西亞第二高樓、去年甫開幕的敦拉薩國際貿易中心（Tun Razak Exchange，簡稱「TRX」） 內，以販售世界各地頂級商品為主，高雄首選紅心芭樂除上架銷售外，還舉辦試吃推廣活動，受到當地消費者的熱烈迴響，直呼「又脆又好吃」，顯示高雄紅心芭樂不僅在品質上備受肯定，更展現了台灣農產品在國際市場上的競爭力和影響力。",
                            DepartmentId = 3,
                            Enable = true,
                            EndDateTime = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertDateTime = new DateTime(2024, 7, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertEmployeeId = 3,
                            StartDateTime = new DateTime(2024, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "台灣好芭 進軍大馬 紅心芭樂魅力席捲吉隆坡",
                            UpdateDateTime = new DateTime(2024, 7, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateEmployeeId = 3
                        });
                });

            modelBuilder.Entity("Kcg.Models.NewsFiles", b =>
                {
                    b.Property<Guid>("NewsFilesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsFilesId");

                    b.ToTable("NewsFiles");
                });

            modelBuilder.Entity("Kcg.Models.TOPMenu", b =>
                {
                    b.Property<Guid>("TOPMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orders")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TOPMenuId");

                    b.ToTable("TOPMenu");

                    b.HasData(
                        new
                        {
                            TOPMenuId = new Guid("9268d41f-6c5c-4bcb-a306-260e802ab1b0"),
                            Icon = "Icon1",
                            Name = "網站導覽",
                            Orders = 1,
                            Url = "a1"
                        },
                        new
                        {
                            TOPMenuId = new Guid("909d9a18-7330-4f74-a0ab-59c8d7c9a6d9"),
                            Icon = "Icon2",
                            Name = "回首頁",
                            Orders = 2,
                            Url = "a2"
                        },
                        new
                        {
                            TOPMenuId = new Guid("6a068953-3822-44d9-ba7d-03676b305a02"),
                            Icon = "Icon3",
                            Name = "English",
                            Orders = 3,
                            Url = "a3"
                        },
                        new
                        {
                            TOPMenuId = new Guid("3572b1bd-5c1d-436d-85cf-9124abe67a0c"),
                            Icon = "Icon4",
                            Name = "雙語詞彙",
                            Orders = 4,
                            Url = "a4"
                        },
                        new
                        {
                            TOPMenuId = new Guid("1d979111-390d-4d28-9fd7-76a860c19f3a"),
                            Icon = "Icon5",
                            Name = "市長信箱",
                            Orders = 5,
                            Url = "a5"
                        },
                        new
                        {
                            TOPMenuId = new Guid("44f4916c-f792-4ba2-bdfa-cfd6c24b2929"),
                            Icon = "Icon6",
                            Name = "洽公導覽",
                            Orders = 6,
                            Url = "a6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
